### ISSUE TITLE
Website not Recognizing Family Membership

### ISSUE THREAD

**Issue by KaguyaIndustries** [Sean-Shmulevich/SpotifyCC#1]
Hey, I wanted to try the tool out but couldn't because its throwing me the error that "this feature is only for premium users" which is odd since Family memberships are Premium Memberships.

**Comment by Sean-Shmulevich** [comment]
I am waiting on approval for Spotify for now, but users are reporting that
the application works great. Because of this Spotify approval process, I
will need to manually add the email associated with your Spotify account
into my developer dashboard. I can do this ASAP. Is the email that you’re
emailing me from the email that’s associated with your Spotify account?

**Comment by KaguyaIndustries** [comment]
Hey, I appreciate the effort but the Spotify Account is hooked to a private mail I'm not willing to share unfortunately.
I will however will follow the Project with a great interest :)!

**Comment by Sean-Shmulevich** [comment]
Please check the readME for specifications about getting approval.
